apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-deployment
  labels:
    app: campaign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campaign
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: campaign
    spec:
      containers:
      - name: campaign
        image: "{IMAGE}"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: campaign-service
spec:
  selector:
    app: campaign
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
