name: ci_api_store

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/api-store/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
