name: ci_api_store

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/api-store/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: azure cli login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy new version
        run: |
          cd ./src/api-store/

          PROJECT_NAME="wwsas2021"

          az aks get-credentials --name "${PROJECT_NAME}-aks" --resource-group "${PROJECT_NAME}-rg" --output none

          echo "Publishing..."

          TAG="v$(date '+%Y%m%d%H%M%S')"

          echo "Start deployment on $PWD"

          ACR_URL=`az acr show --name "${PROJECT_NAME}acr" --resource-group "${PROJECT_NAME}-rg" --query "loginServer" --output tsv`

          IMAGE="${PWD##*/}:${TAG}"

          az acr build -t "${PROJECT_NAME}/${IMAGE}" --registry "${PROJECT_NAME}acr" -f "./Dockerfile" .

          cat ./deploy.yml | sed s/"{IMAGE}"/"${ACR_URL}\/${PROJECT_NAME}\/${IMAGE}"/g | kubectl apply -f -

          echo "...done"
