name: ci_web_frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/web-frontend/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: azure cli login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
